# This file was generated by GoReleaser. DO NOT EDIT.
cask "azlocal" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "c4e4e0037a1a3eea6f3bcdc8b6681dc819337bd27d8e0873a9c5104c32673c81"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
    on_arm do
      sha256 "4a75f086afd2622ba5a212e853c177b854e3568aeb2261a73a245e60ba68f474"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd7baf076d247829e639bd01afd0c9faf6d891629e07ca32971740603021dd6d"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_linux_amd64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
    on_arm do
      sha256 "88ec988e568eb550425dafbac752a074cc40af3511ad3c24c914ad97a3cd15ed"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_linux_arm64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
  end

  name "azlocal"
  desc "Local Azure-like dev environment CLI"
  homepage "https://github.com/DanielTangnes/azlocal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "azlocal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azlocal"]
    end
  end

  # No zap stanza required

end
