# This file was generated by GoReleaser. DO NOT EDIT.
cask "azlocal" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c9eee06b492ab80150000d04b42a8bd392f20927f79ee4ef5a877643015940c0"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
    on_arm do
      sha256 "86550decee246a0a801da11f5c167178b4f448abedcefc439d684bf8787f2174"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
  end

  on_linux do
    on_intel do
      sha256 "b559c38cf89d329953d037fedf9100bd66d054b7f3dcc546952efa16ead49268"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_linux_amd64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
    on_arm do
      sha256 "af13681bd0e00134bf32c49ef21b73887495a1af87b08a62b3e245a75a009815"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_linux_arm64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
  end

  name "azlocal"
  desc "Local Azure-like dev environment CLI"
  homepage "https://github.com/DanielTangnes/azlocal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "azlocal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azlocal"]
    end
  end

  # No zap stanza required

end
