# This file was generated by GoReleaser. DO NOT EDIT.
cask "azlocal" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f68f2e2d47d1691c1672dcec9b8fda34fa4e8b8b125b2f39c13d632b52887f3a"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
    on_arm do
      sha256 "aa1fbbb5885a5a0020942e6a19f6d2b22abd5d9c579e512a9b8bb97f4ca482e1"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
  end

  on_linux do
    on_intel do
      sha256 "18af3251cc9b54b39736b2139ed8fc1b2ba79a2b354ae37ea72e3ec0960cbf23"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_linux_amd64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
    on_arm do
      sha256 "f46469e24fbb2189c5d031aab4b67f6fc1d253b688a31b104508d19bff4549c2"
      url "https://github.com/DanielTangnes/azlocal/releases/download/v#{version}/azlocal_#{version}_linux_arm64.tar.gz",
        verified: "github.com/DanielTangnes/azlocal"
    end
  end

  name "azlocal"
  desc "Local Azure-like dev environment CLI"
  homepage "https://github.com/DanielTangnes/azlocal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "azlocal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azlocal"]
    end
  end

  # No zap stanza required

end
